/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blibliotecapp;

import javax.swing.JFrame;

/**
 *
 * @author erick
 */
public class Busqueda extends javax.swing.JFrame {

    /**
     * Creates new form perfilDatos
     */
    public Busqueda() {
        this.setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresar = new javax.swing.JLabel();
        LBBusqueda = new javax.swing.JLabel();
        TxtPalabra = new javax.swing.JTextField();
        LBCampo = new javax.swing.JLabel();
        CMBCampo = new javax.swing.JComboBox();
        LBFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresarMouseClicked(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 130, 140));

        LBBusqueda.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        LBBusqueda.setText("Palabra(s) a buscar:");
        getContentPane().add(LBBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 230, 50));

        TxtPalabra.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        getContentPane().add(TxtPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 480, 40));

        LBCampo.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        LBCampo.setText("Palabra(s) a buscar:");
        getContentPane().add(LBCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 230, 50));

        CMBCampo.setFont(new java.awt.Font("Calibri Light", 1, 28)); // NOI18N
        CMBCampo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ID de libro", "Titulo", "Autor", "Año" }));
        getContentPane().add(CMBCampo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 480, 80));

        LBFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/surce/busqueda.png"))); // NOI18N
        LBFondo.setText("ss");
        getContentPane().add(LBFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);        
        System.out.println("return to menu");
    }//GEN-LAST:event_regresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Busqueda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CMBCampo;
    private javax.swing.JLabel LBBusqueda;
    private javax.swing.JLabel LBCampo;
    private javax.swing.JLabel LBFondo;
    private javax.swing.JTextField TxtPalabra;
    private javax.swing.JLabel regresar;
    // End of variables declaration//GEN-END:variables
}
