/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blibliotecapp;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author erick
 */
public class Canjear extends javax.swing.JFrame {

    /**
     * Creates new form perfilDatos
     */
    public Canjear() {
        this.setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresar = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        Btllavero = new javax.swing.JLabel();
        Bttasa = new javax.swing.JLabel();
        Btpluma = new javax.swing.JLabel();
        LBpuntos = new javax.swing.JLabel();
        LBpuntaje = new javax.swing.JLabel();
        LBfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresarMouseClicked(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 130, 140));

        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 170, 140));
        getContentPane().add(Btllavero, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 590, 360, 110));
        getContentPane().add(Bttasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 590, 360, 110));

        Btpluma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtplumaMouseClicked(evt);
            }
        });
        getContentPane().add(Btpluma, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, 360, 110));

        LBpuntos.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        LBpuntos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBpuntos.setText("Puntaje Actual");
        getContentPane().add(LBpuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 370, -1));

        LBpuntaje.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        LBpuntaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBpuntaje.setText("0 Pts.");
        getContentPane().add(LBpuntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 370, -1));

        LBfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/surce/nuevasP/cupones E.png"))); // NOI18N
        getContentPane().add(LBfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        VarG.jfIdioma.pausarAudios();
        VarG.jfLogin.setVisible(true);
        VarG.jfLogin.id.requestFocus();  
        System.out.println("return profile data");
        VarG.anActual = VarG.animaciones.get(4);
        VarG.anActual.getImage().flush();
    }//GEN-LAST:event_regresarMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        VarG.jfLogin.setVisible(false);
        this.setVisible(false);
        VarG.jfIdioma.pausarAudios();
        VarG.anActual = VarG.animaciones.get(4);
        VarG.anActual.getImage().flush();
    }//GEN-LAST:event_homeMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        LBpuntaje.setText(Integer.toString(VarG.puntaje)  + " Pts.");
        if(VarG.idioma.equals("espanol")){
            LBfondo.setIcon(new ImageIcon("src/surce/nuevasP/cupones E.png"));
            LBpuntos.setText("Puntaje Actual");
        }else{
            LBfondo.setIcon(new ImageIcon("src/surce/nuevasP/cupones I.png"));
            LBpuntos.setText("Current Score");
        }
    }//GEN-LAST:event_formWindowActivated

    private void BtplumaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtplumaMouseClicked
        
    }//GEN-LAST:event_BtplumaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Canjear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Canjear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Canjear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Canjear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Canjear().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Btllavero;
    private javax.swing.JLabel Btpluma;
    private javax.swing.JLabel Bttasa;
    private javax.swing.JLabel LBfondo;
    private javax.swing.JLabel LBpuntaje;
    private javax.swing.JLabel LBpuntos;
    private javax.swing.JLabel home;
    private javax.swing.JLabel regresar;
    // End of variables declaration//GEN-END:variables
}
