/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blibliotecapp;

/**
 *
 * @author erick
 */
public class Idioma extends javax.swing.JFrame {

    /**
     * Creates new form Idioma
     */
    public Idioma() {
        this.setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ingles = new javax.swing.JLabel();
        aleman = new javax.swing.JLabel();
        frances = new javax.swing.JLabel();
        espanol = new javax.swing.JLabel();
        regresar = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ingles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inglesMouseClicked(evt);
            }
        });
        getContentPane().add(ingles, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 190, 180));

        aleman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alemanMouseClicked(evt);
            }
        });
        getContentPane().add(aleman, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 120, 170, 180));

        frances.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                francesMouseClicked(evt);
            }
        });
        getContentPane().add(frances, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 180, 180));

        espanol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                espanolMouseClicked(evt);
            }
        });
        getContentPane().add(espanol, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 180, 180));

        regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresarMouseClicked(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 120));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/surce/flags.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarMouseClicked
         // TODO add your handling code here:
         this.setVisible(false);
    }//GEN-LAST:event_regresarMouseClicked

    private void espanolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espanolMouseClicked
        // TODO add your handling code here:
        cambiaIdioma("espanol");
    }//GEN-LAST:event_espanolMouseClicked

    private void inglesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inglesMouseClicked
        // TODO add your handling code here:
        cambiaIdioma("ingles");
    }//GEN-LAST:event_inglesMouseClicked

    private void francesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_francesMouseClicked
        // TODO add your handling code here:
        cambiaIdioma("frances");
    }//GEN-LAST:event_francesMouseClicked

    private void alemanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alemanMouseClicked
        // TODO add your handling code here:
        cambiaIdioma("aleman");
    }//GEN-LAST:event_alemanMouseClicked
    public void cambiaIdioma(String idioma){
        VariablesGlobales.idioma=idioma;
        this.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Idioma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Idioma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Idioma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Idioma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Idioma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aleman;
    private javax.swing.JLabel background;
    private javax.swing.JLabel espanol;
    private javax.swing.JLabel frances;
    private javax.swing.JLabel ingles;
    private javax.swing.JLabel regresar;
    // End of variables declaration//GEN-END:variables
}
