/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blibliotecapp;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author erick
 */
public class perfilDatos extends javax.swing.JFrame {

    /**
     * Creates new form perfilDatos
     */
    public perfilDatos() {
        this.setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresar = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LBID = new javax.swing.JLabel();
        LBPuntaje = new javax.swing.JLabel();
        LBNombre = new javax.swing.JLabel();
        LBHistorial = new javax.swing.JLabel();
        LBFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresarMouseClicked(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 130, 140));

        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 170, 140));

        jTable1.setFont(new java.awt.Font("Arial Unicode MS", 0, 20)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Prestamo", "ID Libro", "Titulo", "Fecha Prestamo", "Fecha Devolucion", "Devuelto", "# Renovaciones"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 720, 370));

        LBID.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        LBID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(LBID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 490, 60));

        LBPuntaje.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        LBPuntaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(LBPuntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 490, 60));

        LBNombre.setFont(new java.awt.Font("Calibri", 0, 40)); // NOI18N
        LBNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(LBNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 490, 60));

        LBHistorial.setFont(new java.awt.Font("Rockwell", 1, 60)); // NOI18N
        LBHistorial.setForeground(new java.awt.Color(0, 102, 204));
        LBHistorial.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LBHistorial.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(LBHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 720, 90));

        LBFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/surce/nuevasP/perfil E.png"))); // NOI18N
        getContentPane().add(LBFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        VarG.jfLogin.setVisible(true);
        VarG.jfLogin.id.requestFocus();  
        System.out.println("return profile data");
        VarG.anActual = VarG.animaciones.get(7);
        VarG.anActual.getImage().flush();
    }//GEN-LAST:event_regresarMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        VarG.jfLogin.setVisible(false);
        this.setVisible(false);
        VarG.anActual = VarG.animaciones.get(7);
        VarG.anActual.getImage().flush();
    }//GEN-LAST:event_homeMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if(VarG.idioma.equals("espanol")){
            LBFondo.setIcon(new ImageIcon("src/surce/nuevasP/perfil E.png"));
            LBHistorial.setText("Historial de Prestamos");
            LBNombre.setText(VarG.nombre + " " + VarG.appat + " " + VarG.apmat);
            LBID.setText("ID: " + Integer.toString(VarG.id_usuario));
            LBPuntaje.setText("Puntaje: "+Integer.toString(VarG.puntaje));
        }else{
            LBFondo.setIcon(new ImageIcon("src/surce/nuevasP/perfil I.png"));
            LBHistorial.setText("Borrowed History");
            LBNombre.setText(VarG.nombre + " " + VarG.appat + " " + VarG.apmat);
            LBID.setText("ID: " + Integer.toString(VarG.id_usuario));
            LBPuntaje.setText("Current Points: "+Integer.toString(VarG.puntaje));
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perfilDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perfilDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perfilDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perfilDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perfilDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBFondo;
    private javax.swing.JLabel LBHistorial;
    private javax.swing.JLabel LBID;
    private javax.swing.JLabel LBNombre;
    private javax.swing.JLabel LBPuntaje;
    private javax.swing.JLabel home;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel regresar;
    // End of variables declaration//GEN-END:variables
}
