package blibliotecapp;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alan
 */
public class tDevolucion extends javax.swing.JFrame {

    /**
     * Creates new form tPrestamo
     */
    public tDevolucion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLID1 = new javax.swing.JLabel();
        jLID2 = new javax.swing.JLabel();
        jLID3 = new javax.swing.JLabel();
        jLID4 = new javax.swing.JLabel();
        jLibro1 = new javax.swing.JLabel();
        jLibro2 = new javax.swing.JLabel();
        jLibro3 = new javax.swing.JLabel();
        jLibro4 = new javax.swing.JLabel();
        jLPts1 = new javax.swing.JLabel();
        jLPts2 = new javax.swing.JLabel();
        jLPts3 = new javax.swing.JLabel();
        jLPts4 = new javax.swing.JLabel();
        jLCob1 = new javax.swing.JLabel();
        jLCob2 = new javax.swing.JLabel();
        jLCob3 = new javax.swing.JLabel();
        jLCob4 = new javax.swing.JLabel();
        jLBoton = new javax.swing.JLabel();
        jLBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 210, 80));
        getContentPane().add(jLID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 210, 80));
        getContentPane().add(jLID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 210, 80));
        getContentPane().add(jLID4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 210, 80));
        getContentPane().add(jLibro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 210, 80));
        getContentPane().add(jLibro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 210, 80));
        getContentPane().add(jLibro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 210, 80));
        getContentPane().add(jLibro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 210, 80));
        getContentPane().add(jLPts1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 210, 80));
        getContentPane().add(jLPts2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 210, 80));
        getContentPane().add(jLPts3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 210, 80));
        getContentPane().add(jLPts4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 210, 80));
        getContentPane().add(jLCob1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, 210, 80));
        getContentPane().add(jLCob2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 210, 80));
        getContentPane().add(jLCob3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, 210, 80));
        getContentPane().add(jLCob4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 410, 210, 80));
        getContentPane().add(jLBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, 400, 200));

        jLBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/surce/nuevasP/tDevolucion.png"))); // NOI18N
        getContentPane().add(jLBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tDevolucion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLBackground;
    private javax.swing.JLabel jLBoton;
    private javax.swing.JLabel jLCob1;
    private javax.swing.JLabel jLCob2;
    private javax.swing.JLabel jLCob3;
    private javax.swing.JLabel jLCob4;
    private javax.swing.JLabel jLID1;
    private javax.swing.JLabel jLID2;
    private javax.swing.JLabel jLID3;
    private javax.swing.JLabel jLID4;
    private javax.swing.JLabel jLPts1;
    private javax.swing.JLabel jLPts2;
    private javax.swing.JLabel jLPts3;
    private javax.swing.JLabel jLPts4;
    private javax.swing.JLabel jLibro1;
    private javax.swing.JLabel jLibro2;
    private javax.swing.JLabel jLibro3;
    private javax.swing.JLabel jLibro4;
    // End of variables declaration//GEN-END:variables
}
