/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blibliotecapp;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Alan
 */
public class tLibro extends javax.swing.JFrame {

    /**
     * Creates new form tCupon
     */
    public tLibro() {
        this.setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLImagen = new javax.swing.JLabel();
        jLAutor = new javax.swing.JLabel();
        jLLibro = new javax.swing.JLabel();
        jLID = new javax.swing.JLabel();
        jLBoton = new javax.swing.JLabel();
        jLBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 310, 310));

        jLAutor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLAutor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 240, 80));

        jLLibro.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLLibro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 240, 90));

        jLID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLID, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 240, 80));

        jLBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLBotonMouseClicked(evt);
            }
        });
        getContentPane().add(jLBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 290, 140));

        jLBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/surce/nuevasP/tLibro.png"))); // NOI18N
        getContentPane().add(jLBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.jLAutor.setText(VarG.tiket.getAutor());
        this.jLID.setText(VarG.tiket.getId_libro());
        this.jLLibro.setText(VarG.tiket.getTitulo());
        String route = "src/surce/cover/" + VarG.tiket.getCover() + ".jpg";
        ImageIcon i = new ImageIcon(route);
        Image image = i.getImage(); // transform it 
        Image newimg = image.getScaledInstance(300, 300, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        i = new ImageIcon(newimg);
                
        this.jLImagen.setIcon(i);

        // jLBackground.setIcon(new ImageIcon("src/surce/nuevasP/tCupon.png"));
    }//GEN-LAST:event_formWindowActivated

    private void jLBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLBotonMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLBotonMouseClicked

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        this.setVisible(false);
    }//GEN-LAST:event_formWindowLostFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLAutor;
    private javax.swing.JLabel jLBackground;
    private javax.swing.JLabel jLBoton;
    private javax.swing.JLabel jLID;
    private javax.swing.JLabel jLImagen;
    private javax.swing.JLabel jLLibro;
    // End of variables declaration//GEN-END:variables
}
